# -*- coding: utf-8 -*-
"""
Lista de productos de la canasta basica (INE) que se rastrean en los
supermercados, con el termino de busqueda equivalente para usar en cada
sitio. Los items de comida fuera del hogar (menus del dia, completos,
empanadas, pollo asado, etc.) se dejaron fuera a proposito: el INE los
mide en restaurantes/rotiserias, no se venden como producto de
supermercado y no tiene sentido buscarlos en jumbo.cl.
"""

CANASTA_BASICA = [
    {"nombre_ine": "Arroz", "termino_busqueda": "arroz"},
    {"nombre_ine": "Pan corriente sin envasar", "termino_busqueda": "pan hallulla"},
    {"nombre_ine": "Espiral", "termino_busqueda": "fideos espiral"},
    {"nombre_ine": "Galleta dulce", "termino_busqueda": "galletas dulces"},
    {"nombre_ine": "Galleta no dulce", "termino_busqueda": "galletas de agua"},
    {"nombre_ine": "Torta 15 o 20 personas", "termino_busqueda": "torta cumpleaños"},
    {"nombre_ine": "Prepizza familiar", "termino_busqueda": "prepizza familiar"},
    {"nombre_ine": "Harina de trigo", "termino_busqueda": "harina de trigo"},
    {"nombre_ine": "Avena", "termino_busqueda": "avena"},
    {"nombre_ine": "Asiento", "termino_busqueda": "asiento vacuno"},
    {"nombre_ine": "Carne molida", "termino_busqueda": "carne molida"},
    {"nombre_ine": "Chuleta de cerdo centro o vetada", "termino_busqueda": "chuleta de cerdo"},
    {"nombre_ine": "Costillar de cerdo", "termino_busqueda": "costillar de cerdo"},
    {"nombre_ine": "Pulpa de cerdo", "termino_busqueda": "pulpa de cerdo"},
    {"nombre_ine": "Carne de pavo molida", "termino_busqueda": "pavo molido"},
    {"nombre_ine": "Pechuga de pollo", "termino_busqueda": "pechuga de pollo"},
    {"nombre_ine": "Pollo entero", "termino_busqueda": "pollo entero"},
    {"nombre_ine": "Trutro de pollo", "termino_busqueda": "trutro pollo"},
    {"nombre_ine": "Pulpa de cordero fresco o refrigerado", "termino_busqueda": "pulpa de cordero"},
    {"nombre_ine": "Salchicha y vienesa de ave", "termino_busqueda": "vienesas de ave"},
    {"nombre_ine": "Salchicha y vienesa tradicional", "termino_busqueda": "vienesas"},
    {"nombre_ine": "Longaniza", "termino_busqueda": "longaniza"},
    {"nombre_ine": "Jamón de cerdo", "termino_busqueda": "jamón de cerdo"},
    {"nombre_ine": "Pate", "termino_busqueda": "paté"},
    {"nombre_ine": "Merluza fresca o refrigerada", "termino_busqueda": "merluza"},
    {"nombre_ine": "Choritos frescos o refrigerados en su concha", "termino_busqueda": "choritos"},
    {"nombre_ine": "Jurel en conserva", "termino_busqueda": "jurel en conserva"},
    {"nombre_ine": "Surtido en conserva", "termino_busqueda": "conserva surtido"},
    {"nombre_ine": "Leche líquida entera", "termino_busqueda": "leche entera"},
    {"nombre_ine": "Leche en polvo entera instantánea", "termino_busqueda": "leche en polvo"},
    {"nombre_ine": "Yogurt", "termino_busqueda": "yogurt"},
    {"nombre_ine": "Queso Gouda", "termino_busqueda": "queso gouda"},
    {"nombre_ine": "Quesillo y queso fresco con sal", "termino_busqueda": "quesillo"},
    {"nombre_ine": "Queso crema", "termino_busqueda": "queso crema"},
    {"nombre_ine": "Huevo de gallina", "termino_busqueda": "huevos"},
    {"nombre_ine": "Mantequilla con sal", "termino_busqueda": "mantequilla con sal"},
    {"nombre_ine": "Margarina", "termino_busqueda": "margarina"},
    {"nombre_ine": "Aceite vegetal combinado o puro", "termino_busqueda": "aceite vegetal"},
    {"nombre_ine": "Plátano", "termino_busqueda": "plátano"},
    {"nombre_ine": "Manzana", "termino_busqueda": "manzana"},
    {"nombre_ine": "Maní salado", "termino_busqueda": "maní salado"},
    {"nombre_ine": "Poroto", "termino_busqueda": "porotos"},
    {"nombre_ine": "Lenteja", "termino_busqueda": "lentejas"},
    {"nombre_ine": "Lechuga", "termino_busqueda": "lechuga"},
    {"nombre_ine": "Zapallo", "termino_busqueda": "zapallo"},
    {"nombre_ine": "Limón", "termino_busqueda": "limón"},
    {"nombre_ine": "Palta", "termino_busqueda": "palta"},
    {"nombre_ine": "Tomate", "termino_busqueda": "tomate"},
    {"nombre_ine": "Zanahoria", "termino_busqueda": "zanahoria"},
    {"nombre_ine": "Cebolla nueva", "termino_busqueda": "cebolla"},
    {"nombre_ine": "Choclo congelado", "termino_busqueda": "choclo congelado"},
    {"nombre_ine": "Papa de guarda", "termino_busqueda": "papas"},
    {"nombre_ine": "Azúcar", "termino_busqueda": "azúcar"},
    {"nombre_ine": "Chocolate", "termino_busqueda": "chocolate"},
    {"nombre_ine": "Caramelo", "termino_busqueda": "caramelos"},
    {"nombre_ine": "Helado familiar un sabor", "termino_busqueda": "helado familiar"},
    {"nombre_ine": "Salsa de tomate", "termino_busqueda": "salsa de tomate"},
    {"nombre_ine": "Sucedáneo de café", "termino_busqueda": "café instantáneo"},
    {"nombre_ine": "Te para preparar", "termino_busqueda": "té"},
    {"nombre_ine": "Agua mineral", "termino_busqueda": "agua mineral"},
    {"nombre_ine": "Bebida gaseosa tradicional", "termino_busqueda": "bebida gaseosa"},
    {"nombre_ine": "Bebida energizante", "termino_busqueda": "bebida energética"},
    {"nombre_ine": "Refresco isotónico", "termino_busqueda": "bebida isotónica"},
    {"nombre_ine": "Jugo líquido", "termino_busqueda": "jugo"},
    {"nombre_ine": "Néctar líquido", "termino_busqueda": "néctar"},
    {"nombre_ine": "Refresco en polvo", "termino_busqueda": "jugo en polvo"},
    {"nombre_ine": "Papas fritas", "termino_busqueda": "papas fritas"},
]
